[build]
builder = "nixpacks"

[build.nixpacks]
# Commands to run for a monorepo setup
cmds = [
  "npm install --legacy-peer-deps",
  "cd client && npm install --legacy-peer-deps",
  "cd ../server && npm install --legacy-peer-deps",
  "cd .."
]

[start]
cmd = "node server/server.js"
