[build]
buildCommand = "npm install --legacy-peer-deps && cd client && npm install --legacy-peer-deps && cd ../server && npm install --legacy-peer-deps && cd .."

[deploy]
startCommand = "node server/server.js"
